source 'https://github.com/CocoaPods/Specs.git'

target 'CRRollingLabel_Example', :exclusive => true do
  pod 'CRRollingLabel', :path => '../'
end

target 'CRRollingLabel_Tests', :exclusive => true do
  pod 'CRRollingLabel', :path => '../'

  
end
